Style/Encoding:
  Enabled: false

Style/IndentationWidth:
  Width: 4

Style/AndOr:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'test/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
