source 'https://rubygems.org'

gem 'dalli'
# fast json
gem 'oj'
gem 'oj_mimic_json'
# pretty
gem 'will_paginate-bootstrap'
# pagination
gem 'will_paginate', '~> 3.1.0'
# serialize models for rest api
gem 'active_model_serializers', '~> 0.10.0'
# generate erd diagrams
gem 'erd'
# verificar rotas não usadas e ações dos controlers inuteis
gem 'traceroute'
# pretty tables
gem 'jquery-datatables-rails'
# Create Graphs
gem 'chartkick'
# generate random data!
gem 'faker'
# let models be voted/downvoted
gem 'acts_as_votable'
# country select form
gem 'country_select'
# country codes
gem 'countries'
# Devise forms with bootstrap
gem 'devise-bootstrap-views'
# Annotate ruby model with table atributes (from schema.rb)
gem 'annotate'
# Implement multi table inheritance
gem 'active_record-acts_as', '2.0.1'
# Make the whole website beautiful!
gem 'bootstrap-sass', '~> 3.3.6'
# Make form creation very very easy!!
gem 'simple_form'
# Authentication gem, provide methods to register, login and logout users
gem 'devise'
# Authorization gem, define what each kind of user can do
gem 'cancancan', '~> 1.10'
# well. font awesome
gem 'font-awesome-rails'
# what the hell is this??
gem 'binding_of_caller'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.0.1'
# Use SCSS for stylesheets
gem 'sass-rails', '5.0.6'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use Puma as the app server
gem 'puma'

group :production do
  gem 'pg'
  gem 'rails_12factor'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Show better error messages
  gem 'better_errors'
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
